global with sharing class icDTOMapicsData {
	global String dhaenb {get;set;}		//	Company Number : 47
	global String fechnb {get;set;}		//	Sales Rep Number : 10057
	global String slsnm {get;set;}		//	Sales Rep Name : BRAMPTON - HOUSE
	global String feabbj {get;set;}		//	Customer Number : 24036514
	global String bfhitx {get;set;}		//	Customer Name : D &amp; W FORWARDERS
	global String ikgrpnam {get;set;}	//	Group Name : D &amp; W FORWARDERS
	global String iksupnam {get;set;}	//	Super Group Name : 
	global String ddaitx {get;set;}		//	Item Number : ICR
	global String umstad {get;set;}		//	UOM : 
	global String pid1Aw {get;set;}		//	Product Name : Inter-Company Rental Charge
	global String pid2Aw {get;set;}		//	Item Colour : 
	global String uuccad {get;set;}		//	Rebate Group/Family : 
	global String rcode {get;set;}		//	Rebate Code : 
	global String shpyear {get;set;}	//	Invoice Year : 2017
	global String shpmonth {get;set;}	//	Invoice Month : 7
	global String ddarqt {get;set;}		//	Shipped Quantity : 0.000
	global String dddpva {get;set;}		//	Net Sales Amount : 32356.670
	global String squares {get;set;}	//	Squares : 0.000
	global String curid {get;set;}		//	Currency Id
	global String status {get;set;}		//	Status
}